# Generated by Django 5.0.6 on 2024-06-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featuredphoto',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/featured'),
        ),
    ]
