# Generated by Django 5.0.6 on 2024-06-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
