# Generated by Django 5.0.6 on 2024-06-05 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_created_at_product_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=180)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='api.productfeatured'),
            preserve_default=False,
        ),
    ]
