# Generated by Django 5.0.6 on 2024-06-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=4.7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ratingcount',
            field=models.IntegerField(default=186),
        ),
    ]
